before_script:
  - docker info

build_image:
  script:
    - docker build -t registry.gitlab.com/personalhealthtrain/implementations/germanmii/difuture/incubating/pht/station .
    # TODO run tests
    - docker push registry.gitlab.com/personalhealthtrain/implementations/germanmii/difuture/incubating/pht/station
