version: '3.8'

volumes:
  pg_data:
  blaze_data:

services:
  postgres:
    image: postgres:13
    volumes:
      - ./setup_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  auth:
    image: ghcr.io/tada5hi/authelion-server:latest
    container_name: pht-station-auth
    volumes:
      - ./service_data/auth:/usr/src/app/writable
    ports:
      - '3010:3010'
    environment:
      PORT: 3010
      ADMIN_USER: admin
      ADMIN_PASSWORD: start123
      NODE_ENV: test
      SELF_URL: http://auth:3010/
    command:
      - start

  redis:
    image: redislabs/rejson:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  airflow:
    container_name: station-airflow
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
#    image: ghcr.io/pht-medic/station-airflow:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./airflow/dags:/root/airflow/dags
      - ./S_2_sk.pem:/opt/private_key.pem
      - ./station_data:/opt/station_data
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - AIRFLOW__WEBSERVER__X_FRAME_ENABLED=True
      - MINIO_HOST=minio:9000
      - MINIO_ACCESS_KEY=minio_admin
      - MINIO_SECRET_KEY=minio_admin
      # TODO Change to your own localhost docker bridge ip
      - STATION_API_URL=http://gateway.docker.internal:8000/api
      - AUTH_URL=http://auth:3010/token
      - STATION_PORT=8000
      - STATION_USER=admin
      - STATION_PASSWORD=start123
    ports:
      - "8080:8080"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./station_data:/data

    environment:
      - MINIO_ACCESS_KEY=minio_admin
      - MINIO_SECRET_KEY=minio_admin
      - MINIO_SERVER_URL=http://127.0.0.1:9000
      - MINIO_BROWSER_REDIRECT_URL=http://127.0.0.1:9001

    command: server /data --console-address ":9001"

  blaze-fhir:
    image: "samply/blaze:latest"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      OPENID_PROVIDER_URL: "http://auth:3010/realms/master"
      BASE_URL: "http://localhost:9090"
    ports:
      - "9090:8080"
    volumes:
      - blaze_data:/app/data

