version: "3.8"

# external volume for persisting the station database
volumes:
  pg_pht_station:
    external: True

services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    container_name: pht-station-db
    volumes:
      - C:\Users\Michael Graf\pht\station\setup_scripts\init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_pht_station:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=FnRfgXpRDSgtgzbzT1bl85cyfP8P77Yl

  traefik:
    image: traefik:v2.6
    restart: unless-stopped
    container_name: pht-station-traefik
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      - "8081:8080" # todo check if this is needed
    volumes:
      - C:\Users\Michael Graf\pht\station\configs\traefik\traefik.yml:/etc/traefik/traefik.yml:ro
      - C:\Users\Michael Graf\pht\station\configs\traefik\config.yml:/etc/traefik/config.yml:ro
      - C:\Users\Michael Graf\pht\station\certs:/etc/certs:ro
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik=true

  auth:
    image: ghcr.io/tada5hi/authelion-server:latest
    container_name: pht-station-auth
    restart: unless-stopped
    volumes:
      - C:\Users\Michael Graf\pht\station\service_data\auth:/usr/src/app/packages/backend/api/writable
    ports:
      - "3010:3010"
    environment:
      - ADMIN_PASSWORD=5gPYikUiWh030rLNtgeu0BlYoFpWVBBz
    command:
      - start
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.tls=true
      - traefik.http.routers.auth.rule=Host("station.localhost") && PathPrefix("/auth")
      - traefik.http.services.auth.loadbalancer.server.port=8000

  api:
    image: ghcr.io/pht-medic/station-api:latest
    restart: unless-stopped
    container_name: pht-station-api
    environment:
      - STATION_ID=3b6c97df-0e34-4242-be3a-0a5e3561d8c4
      - STATION_DB=postgresql+psycopg2://admin:FnRfgXpRDSgtgzbzT1bl85cyfP8P77Yl@postgres/pht_station
      - FERNET_KEY=3pQMANDt_8CwXwPE5vwUqwwS7AvvrfNRF_sZbkoGPrk=
      - ENVIRONMENT=development
      - AIRFLOW_API_URL=http://airflow:8080/api/v1/
      - AIRFLOW_USER=admin
      - AIRFLOW_PW=5gPYikUiWh030rLNtgeu0BlYoFpWVBBz
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_USER=minio_access_key
      - MINIO_PW=y9f6fNu9KzEZSAbt9fp2ezldVKDHNoiM
      - REDIS_HOST=redis
      - AUTH_SERVER_HOST=station-auth
      - AUTH_SERVER_PORT=3010
      - AUTH_ROBOT_ID=ce512951-df01-435f-b01e-702fcfeadd10
      - AUTH_ROBOT_SECRET=acno3xl4zloh9om20ywodqsd84ldhsgoz7ur2qs96a3t5zq7gwkct50supqafbsn
      - HARBOR_URL=staging-harbor.tada5hi.net
      - HARBOR_USER=robot$$aotq23y7qcwphcwu542or
      - HARBOR_PW=0j8miBOmILJJCq8oFNgGDTSnMfYO01LN
      - HARBOR_PROJECT=aotq23y7qcwphcwu542or
    ports:
      - "8000:8000"
    labels: 
      - traefik.enable=true
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.rule=Host("station.localhost") && PathPrefix("/api")
      - traefik.http.services.api.loadbalancer.server.port=8000

  frontend:
    image: ghcr.io/pht-medic/station-ui:latest
    restart: unless-stopped
    container_name: pht-station-frontend
    environment:
      - STATION_API_URL=station.localhost/api
      - AUTH_API_URL=station.localhost/auth
    ports:
      - "3000:3000"
    labels: 
      - traefik.enable=true
      - traefik.http.routers.ui.tls=true
      - traefik.http.routers.ui.rule=Host("station.localhost")
      - traefik.http.services.airflow.loadbalancer.server.port=3000

  redis:
    image: redislabs/rejson:latest
    restart: unless-stopped
    container_name: pht-station-redis
    ports:
      - "6379:6379"
    volumes:
      - C:\Users\Michael Graf\pht\station\service_data/redis:/data

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    container_name: pht-station-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
    volumes:
      - C:\Users\Michael Graf\pht\station\station_data:/data
    environment:
      - MINIO_SERVER_URL=http://127.0.0.1:9000
      - MINIO_BROWSER_REDIRECT_URL=http://127.0.0.1:9001 
      - MINIO_ROOT_USER=minio_access_key
      - MINIO_ROOT_PASSWORD=y9f6fNu9KzEZSAbt9fp2ezldVKDHNoiM
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.rule=Host("minio.station.localhost")
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.http.routers.minio-console.tls=true
      - traefik.http.routers.minio-console.rule=Host("minio-console.station.localhost")
      - traefik.http.routers.minio-console.service=minio-console
      - traefik.http.services.minio-console.loadbalancer.server.port=9001

  airflow:
    image: ghcr.io/pht-medic/airflow:latest
    container_name: pht-station-airflow
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\Users\Michael Graf\pht\station\test-key.pem:/opt/private_key.pem
      - C:\Users\Michael Graf\pht\station\configs\airflow.cfg:/root/airflow/airflow.cfg
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - PRIVATE_KEY_PATH=/opt/private_key.pem 
      - STATION_ID=aotq23y7qcwphcwu542or
      - AIRFLOW_USER=admin
      - AIRFLOW_PW=5gPYikUiWh030rLNtgeu0BlYoFpWVBBz
      - HARBOR_URL=staging-harbor.tada5hi.net
      - HARBOR_USER=robot$$aotq23y7qcwphcwu542or
      - HARBOR_PW=0j8miBOmILJJCq8oFNgGDTSnMfYO01LN
    labels: 
      - traefik.enable=true
      - traefik.http.routers.airflow.tls=true
      - traefik.http.routers.airflow.rule=Host("station.localhost") && PathPrefix("/airflow")
      - traefik.http.services.airflow.loadbalancer.server.port=8080

networks:
  default:
    external:
      name: pht-station