version: '3.8'


volumes:
  pg_pht_station:
    external: True

  blaze_data:

services:
  pg_station:
    image: postgres:13
    volumes:
      - ./setup_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_pht_station:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5442:5432"

  airflow:
    container_name: station-airflow
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Station Private Key needs to be set and registered
      # - ./station/station_leipzig_private_key.pem:/opt/private_key.pem
      # Mount the dags directory as a volume
      - ./airflow/dags:/root/airflow/dags
      # - ./station /opt/station
    depends_on:
      - pg_station
    environment:
      - AIRFLOW_HOME=/root/airflow
      - AIRFLOW_USER=admin
      - AIRFLOW_PW=admin
      - FHIR_ADDRESS=https://fhir.personalhealhtrain.de
      - FHIR_USER=fhiruser
      - FHIR_PW=
      - MINIO_URL=
      - MINIO_USER=minio_admin
      - MINIO_PW=minio_admin
      - HARBOR_USER=
      - HARBOR_PW=
      - STATION_DB_CONN_ID=psql_station_db
      - STATION_DB_CONN_TYPE=postgres
      - STATION_DB_HOST=pg_station
      - STATION_DB_USER=admin
      - STATION_DB_SECRET=admin
      - STATION_DB_PORT=5432
      - STATION_DB=postgresql+psycopg2://admin:admin@pg_station:5432/psql_station_db
      - STATION_ID=1
      - STATION_PRIVATE_KEY_PATH=/opt/private_key.pem
      - HARBOR_API_URL=https://harbor.personalhealthtrain.de/api/v2.0
    ports:
      - "8080:8080"

  minio:
    image: minio/minio:latest
    ports:
      - "9001:9000"
    volumes:
      - ./test_data:/data

    environment:
      - MINIO_ACCESS_KEY=minio_admin
      - MINIO_SECRET_KEY=minio_admin

    command: server /data

  fhir-blaze:
    image: samply/blaze
    volumes:
      - blaze_data:/app/data
    environment:
      BASE_URL: "127.0.0.1:8082"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      OPENID_PROVIDER_URL: "https://dev-keycloak.grafm.de/auth/realms/blaze"
    ports:
      - "8082:8080"

