version: '3.8'


volumes:
  pg_pht_station:
    external: True

  fhir-data:


services:

  station:
    build: .
    environment:
      - STATION_ID=dev
      - STATION_DB=postgresql+psycopg2://admin:admin@pg_station/pht_station
      - ENVIRONMENT=production
      - MINIO_URL=minio:9000
      - MINIO_HOST=minio
      - MINIO_USER=minio_admin
      - MINIO_PW=minio_admin
      - FERNET_KEY=XvKQY_wa9EtUh2j8numvvzKzamXLH4DvVmBAkopYdY4=
      - HARBOR_URL=https://dev-harbor.grafm.de
      - HARBOR_USER=admin
      - HARBOR_PW=admin
      - AUTH_SERVER_HOST=station-auth
      - AUTH_SERVER_PORT=3010
      - REDIS_HOST=redis
      - AIRFLOW_USER=admin
      - AIRFLOW_PW=start123
      - STATION_API_HOST=0.0.0.0
      - STATION_API_PORT=8001
    ports:
      - "8001:8001"
    command: [ "./wait-for-it.sh","--timeout=10", "pg_station:5432", "--", "python", "/home/station/run_station.py" ]

  pg_station:
    image: postgres:13
    volumes:
      - ./setup_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_pht_station:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  airflow:
    container_name: station-airflow
    build:
      context: '.'
      dockerfile: './airflow/Dockerfile'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Station Private Key needs to be set and registered
      - ./S_2_sk.pem:/opt/private_key.pem
      # Mount the dags directory as a volume
      - ./airflow/dags:/root/airflow/dags
      # - ./station /opt/station
    depends_on:
      - pg_station
    env_file:
      - .env
#    environment:
#      - FHIR_ADDRESS=$FHIR_SERVER_URL
#      - STATION_ID=$STATION_ID
#      - PRIVATE_KEY_PATH=/opt/private_key.pem
#      - STATION_DATA_DIR=$STATION_DATA_DIR
    ports:
      - "8080:8080"

  auth:
    image: ghcr.io/pht-medic/station-ui:latest
    container_name: station-auth
    volumes:
      - auth_data:/usr/src/app/writable
    ports:
      - '3010:3010'
    environment:
      PORT: 3010
      ADMIN_USER: admin
      ADMIN_PASSWORD: start123
    command:
      - server
      - start

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data

    environment:
      - MINIO_ROOT_USER=minio_admin
      - MINIO_ROOT_PASSWORD=minio_admin

    command: server /data --console-address ":9001"

  redis:
    image: redislabs/rejson:latest
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data
