version: "3.8"

# external volume for persisting the station database
volumes:
  pg_pht_station:
    external: True

services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    container_name: pht-station-db
    volumes:
      - C:\Users\micha\tbi\repos\station\setup_scripts\init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_pht_station:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pw3j5YjdKO2BRKKwE1ELGMITPp73KRkt

  traefik:
    image: traefik:v2.8
    restart: unless-stopped
    container_name: pht-station-traefik
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      - "8081:8080" # todo check if this is needed
    volumes:
      - C:\Users\micha\tbi\repos\station\configs\traefik\traefik.yml:/etc/traefik/traefik.yml:ro
      - C:\Users\micha\tbi\repos\station\configs\traefik\config.yml:/etc/traefik/config.yml:ro
      - C:\Users\micha\tbi\repos\station\certs:/etc/certs:ro
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik=true

  auth:
    image: ghcr.io/tada5hi/authup-server:latest
    container_name: pht-station-auth
    restart: unless-stopped
    volumes:
      - C:\Users\micha\tbi\repos\station\service_data\auth:/usr/src/app/writable
    ports:
      - "3010:3010"
    environment:
      - ADMIN_PASSWORD=6CKzZlzmRFsnYTEAqabSphHHE6W4O0Xd
      - NODE_ENV=production
      - PUBLIC_URL=station.localhost/auth
      - AUTHORIZATION_REDIRECT_URL=station.localhost
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=postgres
      - TYPEORM_USERNAME=admin
      - TYPEORM_PASSWORD=pw3j5YjdKO2BRKKwE1ELGMITPp73KRkt
      - TYPEORM_DATABASE=auth
      - TYPEORM_PORT=5432
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=false
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.tls=true
      - traefik.http.routers.auth.rule=Host("station.localhost") && PathPrefix("/auth")
      - traefik.http.services.auth.loadbalancer.server.port=3010
      - traefik.http.middlewares.auth-stripprefix.stripprefix.prefixes=/auth
      - traefik.http.routers.auth.middlewares=auth-stripprefix@docker
    command:
      - start

  api:
    image: ghcr.io/pht-medic/station-api:latest
    restart: unless-stopped
    container_name: pht-station-api
    environment:
      - STATION_ID=65681b61-cee3-4064-b925-08fc01507f81
      - STATION_DB=postgresql+psycopg2://admin:pw3j5YjdKO2BRKKwE1ELGMITPp73KRkt@postgres/pht_station
      - FERNET_KEY=SsUNUOXR1_HALeD2-4eCEYYnQiuMWxIpTrjxz7lsg8U=
      - ENVIRONMENT=development
      - AIRFLOW_API_URL=https://station.localhost/airflow/api/v1/
      - AIRFLOW_USER=admin
      - AIRFLOW_PW=Nk5jMb4WiAT1qrkns2bbeEGp6lcIqqfL
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_USER=admin
      - MINIO_PW=E8kW6HTSszLFj7lD5HlH8544hjfFUnA6
      - REDIS_HOST=redis
      - AUTH_SERVER_HOST=https://station.localhost/auth
      - AUTH_SERVER_PORT=3010
      - AUTH_ROBOT_ID=b2ce7e24-9846-43df-a574-d4f3f8790611
      - AUTH_ROBOT_SECRET=yy6nrq2zhgodufagd39byz2ieqyodcbehqcrbuwvfxqdis9xn3u6y4e3eeh1t5t7
      - HARBOR_URL=staging-harbor.tada5hi.net
      - HARBOR_USER=robot$$10fqi2nugnog5nak0ylec
      - HARBOR_PW=jFluVcDzsOofUIiBXa4yyW49NvA2BJHp
      - HARBOR_PROJECT=10fqi2nugnog5nak0ylec
      - CENTRAL_API_URL=https://staging-pht.tada5hi.net/api
      - STATION_ROBOT_ID=9e93aa99-33f9-4b46-a361-d4d56d5893a4
      - STATION_ROBOT_SECRET=pXUrsHktU5XrV0.ii1NbwkzP!JRn_jFrEC3.Lljb9i.fKp5m5yxNTio4TGSQ4NxE
    ports:
      - "8000:8000"
    labels: 
      - traefik.enable=true
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.rule=Host("station.localhost") && PathPrefix("/api")
      - traefik.http.services.api.loadbalancer.server.port=8000

  frontend:
    image: ghcr.io/pht-medic/station-ui:latest
    restart: unless-stopped
    container_name: pht-station-frontend
    environment:
      - STATION_API_URL=https://station.localhost/api
      - AUTH_API_URL=https://station.localhost/auth
    ports:
      - "3000:3000"
    labels: 
      - traefik.enable=true
      - traefik.http.routers.ui.tls=true
      - traefik.http.routers.ui.rule=Host("station.localhost") && !PathPrefix("/api") && !PathPrefix("/auth") && !PathPrefix("/airflow") && !PathPrefix("/fhir-servers")
      - traefik.http.services.ui.loadbalancer.server.port=3000
  redis:
    image: redislabs/rejson:latest
    restart: unless-stopped
    container_name: pht-station-redis
    ports:
      - "6379:6379"
    volumes:
      - C:\Users\micha\tbi\repos\station\service_data/redis:/data

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    container_name: pht-station-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
    volumes:
      - C:\Users\micha\tbi\repos\station\station_data:/data
    environment:
      - MINIO_SERVER_URL=http://127.0.0.1:9000
      - MINIO_BROWSER_REDIRECT_URL=http://127.0.0.1:9001 
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=E8kW6HTSszLFj7lD5HlH8544hjfFUnA6
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.rule=Host("minio.station.localhost")
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.http.routers.minio-console.tls=true
      - traefik.http.routers.minio-console.rule=Host("minio-console.station.localhost")
      - traefik.http.routers.minio-console.service=minio-console
      - traefik.http.services.minio-console.loadbalancer.server.port=9001

  airflow:
    image: ghcr.io/pht-medic/airflow:latest
    container_name: pht-station-airflow
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\Users\micha\tbi\repos\station\test-key.pem:/opt/private_key.pem
      - C:\Users\micha\tbi\repos\station\configs\airflow.cfg:/root/airflow/airflow.cfg
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - PRIVATE_KEY_PATH=/opt/private_key.pem 
      - STATION_ID=10fqi2nugnog5nak0ylec
      - AIRFLOW_USER=admin
      - AIRFLOW_PW=Nk5jMb4WiAT1qrkns2bbeEGp6lcIqqfL
      - HARBOR_URL=staging-harbor.tada5hi.net
      - HARBOR_USER=robot$$10fqi2nugnog5nak0ylec
      - HARBOR_PW=jFluVcDzsOofUIiBXa4yyW49NvA2BJHp
    labels: 
      - traefik.enable=true
      - traefik.http.routers.airflow.tls=true
      - traefik.http.routers.airflow.rule=Host("station.localhost") && PathPrefix("/airflow")
      - traefik.http.services.airflow.loadbalancer.server.port=8080

networks:
  default:
    name: pht-station