version: '3.8'


volumes:
  pg_pht_station:
    external: True

  fhir-data:
services:

  station:
    build: .
    environment:
      - STATION_DB=postgresql+psycopg2://admin:admin@pg_station/pht_station
      - ENVIRONMENT=dev
    env_file:
      - .env
    ports:
      - "8001:8001"
    command: [ "./wait-for-it.sh","--timeout=10", "pg_station:5432", "--", "python", "/home/station/run_station.py" ]

  pg_station:
    image: postgres:13
    volumes:
      - ./setup_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_pht_station:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  airflow:
    build:
      context: '.'
      dockerfile: './airflow/Dockerfile'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Station Private Key needs to be set and registered
      - ./S_2_sk.pem:/opt/private_key.pem
      # Mount the dags directory as a volume
      - ./airflow/dags:/root/airflow/dags
      # - ./station /opt/station
    depends_on:
      - pg_station
    env_file:
      - .env
    environment:
      - FHIR_ADDRESS=$FHIR_SERVER_URL
      - STATION_ID=$STATION_ID
      - STATION_PRIVATE_KEY_PATH=/opt/private_key.pem
      - STATION_DATA_DIR=$STATION_DATA_DIR
    ports:
      - "8080:8080"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - ./test_data:/data

    environment:
      - MINIO_ACCESS_KEY=minio_admin
      - MINIO_SECRET_KEY=minio_admin

    command: server /data

  fhir-blaze:
    image: samply/blaze
    volumes:
      - fhir-data:/app/data
    ports:
      - "8081:8080"

