http:
  routers:
    traefik:
      rule: "Host(`traefik.station.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "station.localhost"
            sans:
              - "*.station.localhost"


tls:
  certificates:
    
    - certFile: "certs/cert.pem"
      keyFile: "certs/key.pem"
    
