global:
  sendAnonymousUsage: false

api:
  dashboard: True
  insecure: True

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: pht-station

  file:
    filename: /etc/traefik/config.yml
    watch: true

log:
  level: DEBUG
  format: common

accessLog: {}

entryPoints:
  http:
    address: ":80"
    
    http:
      redirections:
       entryPoint:
         to: https
         scheme: https
    
  
  https:
    address: ":443"
  