"""initial migration

Revision ID: 295c0371260d
Revises: 
Create Date: 2021-06-11 07:37:20.416083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295c0371260d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('storage_type', sa.String(), nullable=True),
    sa.Column('access_path', sa.String(), nullable=True),
    sa.Column('n_items', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_table('docker_train_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('airflow_config_json', sa.String(), nullable=True),
    sa.Column('cpu_requirements', sa.String(), nullable=True),
    sa.Column('gpu_requirements', sa.String(), nullable=True),
    sa.Column('auto_execute', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docker_train_configs_id'), 'docker_train_configs', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_user', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('docker_trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['docker_train_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docker_trains_id'), 'docker_trains', ['id'], unique=False)
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_table('cyphers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('cypher', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cyphers_id'), 'cyphers', ['id'], unique=False)
    op.create_table('dl_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_src', sa.String(), nullable=True),
    sa.Column('model_logs', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id')
    )
    op.create_index(op.f('ix_dl_models_id'), 'dl_models', ['id'], unique=False)
    op.create_table('docker_train_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('airflow_dag_run', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['docker_trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docker_train_executions_id'), 'docker_train_executions', ['id'], unique=False)
    op.create_table('docker_train_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('last_execution', sa.DateTime(), nullable=True),
    sa.Column('num_executions', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['docker_trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docker_train_states_id'), 'docker_train_states', ['id'], unique=False)
    op.create_table('key_broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=True),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('signing_key', sa.String(), nullable=True),
    sa.Column('sharing_key', sa.String(), nullable=True),
    sa.Column('key_signature', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_broadcasts_id'), 'key_broadcasts', ['id'], unique=False)
    op.create_table('torch_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('model_path', sa.String(), nullable=True),
    sa.Column('model_src', sa.String(), nullable=True),
    sa.Column('lightning_model_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id')
    )
    op.create_index(op.f('ix_torch_models_id'), 'torch_models', ['id'], unique=False)
    op.create_table('train_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('signing_key', sa.String(), nullable=True),
    sa.Column('sharing_key', sa.String(), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('key_broadcast', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_states_id'), 'train_states', ['id'], unique=False)
    op.create_table('model_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dl_model_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('checkpoint_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dl_model_id'], ['dl_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_checkpoints_id'), 'model_checkpoints', ['id'], unique=False)
    op.create_table('torch_model_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('checkpoint', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['torch_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_torch_model_checkpoints_id'), 'torch_model_checkpoints', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_torch_model_checkpoints_id'), table_name='torch_model_checkpoints')
    op.drop_table('torch_model_checkpoints')
    op.drop_index(op.f('ix_model_checkpoints_id'), table_name='model_checkpoints')
    op.drop_table('model_checkpoints')
    op.drop_index(op.f('ix_train_states_id'), table_name='train_states')
    op.drop_table('train_states')
    op.drop_index(op.f('ix_torch_models_id'), table_name='torch_models')
    op.drop_table('torch_models')
    op.drop_index(op.f('ix_key_broadcasts_id'), table_name='key_broadcasts')
    op.drop_table('key_broadcasts')
    op.drop_index(op.f('ix_docker_train_states_id'), table_name='docker_train_states')
    op.drop_table('docker_train_states')
    op.drop_index(op.f('ix_docker_train_executions_id'), table_name='docker_train_executions')
    op.drop_table('docker_train_executions')
    op.drop_index(op.f('ix_dl_models_id'), table_name='dl_models')
    op.drop_table('dl_models')
    op.drop_index(op.f('ix_cyphers_id'), table_name='cyphers')
    op.drop_table('cyphers')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_docker_trains_id'), table_name='docker_trains')
    op.drop_table('docker_trains')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_docker_train_configs_id'), table_name='docker_train_configs')
    op.drop_table('docker_train_configs')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
