FROM bitnami/python:3.11
MAINTAINER michael.graf@uni-tuebingen.de

# update the image
RUN apt -y update && apt-get -y install software-properties-common && \
    apt-get upgrade -yqq && \
    apt-get install -yqq --no-install-recommends --no-install-suggests \
        libffi-dev \
        libpq-dev \
        build-essential \
        apt-utils \
        locales \
        curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apt/archives/*

# install python



# set poetry environment variables
ENV POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_VIRTUALENVS_IN_PROJECT=false \
    POETRY_NO_INTERACTION=1 \
    POETRY_VERSION=1.3.2


RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="$PATH:$POETRY_HOME/bin"


COPY . /home/station
WORKDIR /home/station
RUN poetry install

ENV PATH="$PATH:$POETRY_HOME/bin"
CMD ["python", "/home/station/station/app/run_station.py"]