# configure station variables
station_id: "your_station_id"
host: "127.0.0.1"
port: "8001"
db: "postgresql+psycopg2://admin:admin@pg_station/pht_station"
environment: "production"
fernet_key: 'your_fernet_key'
# Configure the connection to the authentication server
auth:
  host: "127.0.0.1"
  port: 3010
  robot_id: "your_robot_id"
  robot_secret: '**********'

# Configure connection to central ui
central_ui:
  api_url: "https://central-ui.example.com"
  client_id: "central_ui_client_id"
  client_secret: "central_ui_client_secret"

# configure airflow connection
airflow:
  host: "airflow"
  port: 8080
  username: "admin"
  password: "admin"
# configure minio connection
minio:
  host: "minio"
  port: 9000
  access_key: "minio_access_key"
  secret_key: "secret_key"
# Configure the connection to the central container registry
registry:
  address: "http://registry.example.com"
  password: "registry_password"
  user: "registry_user"
